In [18]:
import pandas as pd

# DATA SPLIT

In [29]:
data_class=pd.read_csv('/home/fsc/Desktop/PD_Project_UofL/PD_DATA/MODELS DEVELOPMENT/DATA FOR MODELS/Subject_Data.csv')
data_class=data_class[['PATNO',"Visit ID",'UPDRS_III_ProgressionType']]
data_class.head(3)

    PATNO Visit ID UPDRS_III_ProgressionType
0  100006  V04_V06       Substantial improv.
1  100007  V04_V06       Substantial improv.
2  100012  V04_V06    No significant change.

# Subject Data

In [19]:
subject_data = pd.read_csv('/home/fsc/Desktop/PD_Project_UofL/PD_DATA/MODELS DEVELOPMENT/DATA FOR MODELS/Subject_Data.csv')
subject_data.head(3)

,PATNO,Visit ID,Sporadic PD at Enrollment,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,...,Delta_DBP,Delta_HR,Ortostatic_Hypotension,UPDRS_I_Class,UPDRS_II_Class,UPDRS_III_Class,UPDRS_IV_Class,UPDRS_I_ProgressionType,UPDRS_II_ProgressionType,UPDRS_III_ProgressionType
0,100006,V04_V06,1,0,0,0,0,0,1965,0,...,0.0,10.0,False,Mild,Mild,Mild,Mild,Substantial progress.,Substantial improv.,Substantial improv.
1,100007,V04_V06,1,0,0,0,0,0,1953,1,...,18.0,-3.0,False,Mild,Mild,Mild,Mild,No significant change.,Substantial improv.,Substantial improv.
2,100012,V04_V06,1,0,0,0,0,0,1955,0,...,-9.0,5.0,False,Mild,Mild,Mild,Mild,No significant change.,No significant change.,No significant change.

In [20]:
subject_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 50 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   PATNO                                                 911 non-null    int64
 1   Visit ID                                              911 non-null    object
 2   Sporadic PD at Enrollment                             911 non-null    int64
 3   RBD at Enrollment                                     911 non-null    int64
 4   Parkin Mutation at Enrollment                         911 non-null    int64
 5   LRRK2 Mutation at Enrollment                          911 non-null    int64
 6   SNCA Mutation at Enrollment                           911 non-null    int64
 7   GBA Mutation at Enrollment                            911 non-null    int64
 8   Birth Date                                            911 non-null    int64
 9   Sex of participant at birth                           911 non-null    int64
 10  Identify self as Asian                                911 non-null    int64
 11  Identify self as Black/African American               911 non-null    int64
 12  Identify self as Hawaiian/Other Pacific Islander      911 non-null    int64
 13  Identify self as American Indian/Alaska Native        911 non-null    int64
 14  Identify self as White                                911 non-null    int64
 15  Education_Years                                       911 non-null    float64
 16  AGE_AT_VISIT                                          911 non-null    float64
 17  Height (cm)                                           911 non-null    float64
 18  Weight (kg)                                           911 non-null    float64
 19  Temperature (Celsius)                                 911 non-null    float64
 20  Supine BP - systolic (mmHg)                           911 non-null    float64
 21  Supine BP - diastolic (mmHg)                          911 non-null    float64
 22  Supine heart rate (bpm)                               911 non-null    float64
 23  Standing BP - systolic (mmHg)                         911 non-null    float64
 24  Standing BP - diastolic (mmHg)                        911 non-null    float64
 25  Standing heart rate (bpm)                             911 non-null    float64
 26  MDS-UPDRS Part I (Patient Questionnaire) Total Score  911 non-null    int64
 27  MDS-UPDRS Part II Total Score                         911 non-null    float64
 28  MDS-UPDRS Part III Total Score                        911 non-null    int64
 29  MDS-UPDRS Part IV Total Score                         911 non-null    float64
 30  MDS-UPDRS Total Score 1YearProg                       911 non-null    float64
 31  UPDRS_III_1YearProg                                   911 non-null    int64
 32  MDS-UPDRS Total Score                                 911 non-null    float64
 33  Δ TOTAL_UPDRS_1Y                                      911 non-null    float64
 34  Δ UPDRS_I_1Y                                          911 non-null    int64
 35  Δ UPDRS_II_1Y                                         911 non-null    float64
 36  Δ UPDRS_III_1Y                                        911 non-null    int64
 37  Δ UPDRS_IV_1Y                                         911 non-null    float64
 38  BMI                                                   911 non-null    float64
 39  Delta_SBP                                             911 non-null    float64
 40  Delta_DBP                                             911 non-null    float64
 41  Delta_HR                                              911 non-null    float64
 42  Ortostatic_Hypotension                                911 non-null    bool
 43  UPDRS_I_Class                                         911 non-null    object
 44  UPDRS_II_Class                                        911 non-null    object
 45  UPDRS_III_Class                                       911 non-null    object
 46  UPDRS_IV_Class                                        911 non-null    object
 47  UPDRS_I_ProgressionType                               911 non-null    object
 48  UPDRS_II_ProgressionType                              911 non-null    object
 49  UPDRS_III_ProgressionType                             911 non-null    object
dtypes: bool(1), float64(22), int64(19), object(8)
memory usage: 349.8+ KB

In [21]:
numeric_cols = subject_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = subject_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['PATNO', 'Sporadic PD at Enrollment', 'RBD at Enrollment', 'Parkin Mutation at Enrollment', 'LRRK2 Mutation at Enrollment', 'SNCA Mutation at Enrollment', 'GBA Mutation at Enrollment', 'Birth Date', 'Sex of participant at birth', 'Identify self as Asian', 'Identify self as Black/African American', 'Identify self as Hawaiian/Other Pacific Islander', 'Identify self as American Indian/Alaska Native', 'Identify self as White', 'Education_Years', 'AGE_AT_VISIT', 'Height (cm)', 'Weight (kg)', 'Temperature (Celsius)', 'Supine BP - systolic (mmHg)', 'Supine BP - diastolic (mmHg)', 'Supine heart rate (bpm)', 'Standing BP - systolic (mmHg)', 'Standing BP - diastolic (mmHg)', 'Standing heart rate (bpm)', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score', 'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg', 'MDS-UPDRS Total Score', 'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y', 'BMI', 'Delta_SBP', 'Delta_DBP', 'Delta_HR']
Categorical Columns: ['Visit ID', 'Ortostatic_Hypotension', 'UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class', 'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType', 'UPDRS_III_ProgressionType']

## Data Selection

In [22]:
subject_data.drop(columns=['Sporadic PD at Enrollment',
                           'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType',
                           'Identify self as Asian', 'Identify self as Black/African American', 
                           'Identify self as Hawaiian/Other Pacific Islander', 'Identify self as American Indian/Alaska Native',
                           'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg',
                           'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y','Delta_SBP',
                           'Delta_DBP', 'Delta_HR', 'Height (cm)', 'Weight (kg)',
                           'Temperature (Celsius)', 'Supine BP - systolic (mmHg)', 'Supine BP - diastolic (mmHg)', 
                           'Supine heart rate (bpm)', 'Standing BP - systolic (mmHg)', 'Standing BP - diastolic (mmHg)', 'Standing heart rate (bpm)',
                           'UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class'
                           ], inplace=True)
subject_data.head(3)

,PATNO,Visit ID,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,Identify self as White,Education_Years,AGE_AT_VISIT,MDS-UPDRS Part I (Patient Questionnaire) Total Score,MDS-UPDRS Part II Total Score,MDS-UPDRS Part III Total Score,MDS-UPDRS Part IV Total Score,MDS-UPDRS Total Score,BMI,Ortostatic_Hypotension,UPDRS_III_ProgressionType
0,100006,V04_V06,0,0,0,0,0,1965,0,1,15.0,56.7,8,9.0,17,2.0,36.0,35.493827,False,Substantial improv.
1,100007,V04_V06,0,0,0,0,0,1953,1,1,19.0,68.4,2,7.0,23,0.0,32.0,22.985398,False,Substantial improv.
2,100012,V04_V06,0,0,0,0,0,1955,0,1,18.0,67.0,6,5.0,14,0.0,25.0,31.130098,False,No significant change.

In [25]:
subject_data['UPDRS_III_ProgressionType'].value_counts()

UPDRS_III_ProgressionType
No significant change.    360
Substantial improv.       326
Substantial progress.     225
Name: count, dtype: int64

In [26]:
numeric_cols = subject_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = subject_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

#'Ortostatic_Hypotension'
subject_data['Ortostatic_Hypotension'] = subject_data['Ortostatic_Hypotension'].map({True: 1, False: 0})
# 'UPDRS_III_ProgressionType'
subject_data['UPDRS_III_ProgressionType'] = subject_data['UPDRS_III_ProgressionType'].map({'Substantial improv.': -1, 'No significant change.': 0,'Substantial progress.': 1})
subject_data.head(3)

Numeric Columns: ['PATNO', 'RBD at Enrollment', 'Parkin Mutation at Enrollment', 'LRRK2 Mutation at Enrollment', 'SNCA Mutation at Enrollment', 'GBA Mutation at Enrollment', 'Birth Date', 'Sex of participant at birth', 'Identify self as White', 'Education_Years', 'AGE_AT_VISIT', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score', 'MDS-UPDRS Total Score', 'BMI']
Categorical Columns: ['Visit ID', 'Ortostatic_Hypotension', 'UPDRS_III_ProgressionType']

,PATNO,Visit ID,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,Identify self as White,Education_Years,AGE_AT_VISIT,MDS-UPDRS Part I (Patient Questionnaire) Total Score,MDS-UPDRS Part II Total Score,MDS-UPDRS Part III Total Score,MDS-UPDRS Part IV Total Score,MDS-UPDRS Total Score,BMI,Ortostatic_Hypotension,UPDRS_III_ProgressionType
0,100006,V04_V06,0,0,0,0,0,1965,0,1,15.0,56.7,8,9.0,17,2.0,36.0,35.493827,0,-1
1,100007,V04_V06,0,0,0,0,0,1953,1,1,19.0,68.4,2,7.0,23,0.0,32.0,22.985398,0,-1
2,100012,V04_V06,0,0,0,0,0,1955,0,1,18.0,67.0,6,5.0,14,0.0,25.0,31.130098,0,0

# Motor Data

# Cognitive Data

# Sleep Data