In [36]:
import pandas as pd
from pathlib import Path
import json
from sklearn.model_selection import train_test_split

In [37]:
ROOT = Path.cwd().parent
subject='DATA_RAW_MODELS/Subject_Data.csv'
motor='DATA_RAW_MODELS/Motor_Data.csv'
cognitive='DATA_RAW_MODELS/Cognitive_Data.csv'
sleep='DATA_RAW_MODELS/Sleep_Data.csv'
ledd='DATA_RAW_MODELS/LEDD_Medication_Data.csv'

# DATA SPLIT

In [38]:
data_class=pd.read_csv(ROOT / subject)
data_class=data_class[['PATNO',"Visit ID",'UPDRS_III_ProgressionType']]
data_class.head(3)

    PATNO Visit ID UPDRS_III_ProgressionType
0  100006  V04_V06       Substantial improv.
1  100007  V04_V06       Substantial improv.
2  100012  V04_V06    No significant change.

In [39]:
X=data_class[['PATNO','Visit ID']]
y=data_class['UPDRS_III_ProgressionType']

X_train, X_test, y_train, y_test = train_test_split(
    X, y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

Subjects_train = (X_train['PATNO'].astype(str) + '_' + X_train['Visit ID'].astype(str)).tolist()

Subjects_test = (X_test['PATNO'].astype(str) + '_' + X_test['Visit ID'].astype(str)).tolist()


data = {
    "Train_80": Subjects_train,
    "Test_20": Subjects_test
}

with open(ROOT / 'DATA_RAW_MODELS/Data_split.json', "w", encoding="utf-8") as archivo:
    json.dump(data, archivo, indent=4, ensure_ascii=False)

# Subject Data

In [40]:
subject_data = pd.read_csv(ROOT / subject)
subject_data.head(3)

,PATNO,Visit ID,Sporadic PD at Enrollment,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,...,Delta_DBP,Delta_HR,Ortostatic_Hypotension,UPDRS_I_Class,UPDRS_II_Class,UPDRS_III_Class,UPDRS_IV_Class,UPDRS_I_ProgressionType,UPDRS_II_ProgressionType,UPDRS_III_ProgressionType
0,100006,V04_V06,1,0,0,0,0,0,1965,0,...,0.0,10.0,False,Mild,Mild,Mild,Mild,Substantial progress.,Substantial improv.,Substantial improv.
1,100007,V04_V06,1,0,0,0,0,0,1953,1,...,18.0,-3.0,False,Mild,Mild,Mild,Mild,No significant change.,Substantial improv.,Substantial improv.
2,100012,V04_V06,1,0,0,0,0,0,1955,0,...,-9.0,5.0,False,Mild,Mild,Mild,Mild,No significant change.,No significant change.,No significant change.

In [41]:
subject_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 911 entries, 0 to 910
Data columns (total 50 columns):
 #   Column                                                Non-Null Count  Dtype
---  ------                                                --------------  -----
 0   PATNO                                                 911 non-null    int64
 1   Visit ID                                              911 non-null    object
 2   Sporadic PD at Enrollment                             911 non-null    int64
 3   RBD at Enrollment                                     911 non-null    int64
 4   Parkin Mutation at Enrollment                         911 non-null    int64
 5   LRRK2 Mutation at Enrollment                          911 non-null    int64
 6   SNCA Mutation at Enrollment                           911 non-null    int64
 7   GBA Mutation at Enrollment                            911 non-null    int64
 8   Birth Date                                            911 non-null    int64
 9   Sex of participant at birth                           911 non-null    int64
 10  Identify self as Asian                                911 non-null    int64
 11  Identify self as Black/African American               911 non-null    int64
 12  Identify self as Hawaiian/Other Pacific Islander      911 non-null    int64
 13  Identify self as American Indian/Alaska Native        911 non-null    int64
 14  Identify self as White                                911 non-null    int64
 15  Education_Years                                       911 non-null    float64
 16  AGE_AT_VISIT                                          911 non-null    float64
 17  Height (cm)                                           911 non-null    float64
 18  Weight (kg)                                           911 non-null    float64
 19  Temperature (Celsius)                                 911 non-null    float64
 20  Supine BP - systolic (mmHg)                           911 non-null    float64
 21  Supine BP - diastolic (mmHg)                          911 non-null    float64
 22  Supine heart rate (bpm)                               911 non-null    float64
 23  Standing BP - systolic (mmHg)                         911 non-null    float64
 24  Standing BP - diastolic (mmHg)                        911 non-null    float64
 25  Standing heart rate (bpm)                             911 non-null    float64
 26  MDS-UPDRS Part I (Patient Questionnaire) Total Score  911 non-null    int64
 27  MDS-UPDRS Part II Total Score                         911 non-null    float64
 28  MDS-UPDRS Part III Total Score                        911 non-null    int64
 29  MDS-UPDRS Part IV Total Score                         911 non-null    float64
 30  MDS-UPDRS Total Score 1YearProg                       911 non-null    float64
 31  UPDRS_III_1YearProg                                   911 non-null    int64
 32  MDS-UPDRS Total Score                                 911 non-null    float64
 33  Δ TOTAL_UPDRS_1Y                                      911 non-null    float64
 34  Δ UPDRS_I_1Y                                          911 non-null    int64
 35  Δ UPDRS_II_1Y                                         911 non-null    float64
 36  Δ UPDRS_III_1Y                                        911 non-null    int64
 37  Δ UPDRS_IV_1Y                                         911 non-null    float64
 38  BMI                                                   911 non-null    float64
 39  Delta_SBP                                             911 non-null    float64
 40  Delta_DBP                                             911 non-null    float64
 41  Delta_HR                                              911 non-null    float64
 42  Ortostatic_Hypotension                                911 non-null    bool
 43  UPDRS_I_Class                                         911 non-null    object
 44  UPDRS_II_Class                                        911 non-null    object
 45  UPDRS_III_Class                                       911 non-null    object
 46  UPDRS_IV_Class                                        911 non-null    object
 47  UPDRS_I_ProgressionType                               911 non-null    object
 48  UPDRS_II_ProgressionType                              911 non-null    object
 49  UPDRS_III_ProgressionType                             911 non-null    object
dtypes: bool(1), float64(22), int64(19), object(8)
memory usage: 349.8+ KB

In [42]:
numeric_cols = subject_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = subject_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['PATNO', 'Sporadic PD at Enrollment', 'RBD at Enrollment', 'Parkin Mutation at Enrollment', 'LRRK2 Mutation at Enrollment', 'SNCA Mutation at Enrollment', 'GBA Mutation at Enrollment', 'Birth Date', 'Sex of participant at birth', 'Identify self as Asian', 'Identify self as Black/African American', 'Identify self as Hawaiian/Other Pacific Islander', 'Identify self as American Indian/Alaska Native', 'Identify self as White', 'Education_Years', 'AGE_AT_VISIT', 'Height (cm)', 'Weight (kg)', 'Temperature (Celsius)', 'Supine BP - systolic (mmHg)', 'Supine BP - diastolic (mmHg)', 'Supine heart rate (bpm)', 'Standing BP - systolic (mmHg)', 'Standing BP - diastolic (mmHg)', 'Standing heart rate (bpm)', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score', 'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg', 'MDS-UPDRS Total Score', 'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y', 'BMI', 'Delta_SBP', 'Delta_DBP', 'Delta_HR']
Categorical Columns: ['Visit ID', 'Ortostatic_Hypotension', 'UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class', 'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType', 'UPDRS_III_ProgressionType']

## Data Selection

In [43]:
subject_data.drop(columns=['Sporadic PD at Enrollment',
                           'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType',
                           'Identify self as Asian', 'Identify self as Black/African American', 
                           'Identify self as Hawaiian/Other Pacific Islander', 'Identify self as American Indian/Alaska Native',
                           'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg',
                           'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y','Delta_SBP',
                           'Delta_DBP', 'Delta_HR', 'Height (cm)', 'Weight (kg)',
                           'Temperature (Celsius)', 'Supine BP - systolic (mmHg)', 'Supine BP - diastolic (mmHg)', 
                           'Supine heart rate (bpm)', 'Standing BP - systolic (mmHg)', 'Standing BP - diastolic (mmHg)', 'Standing heart rate (bpm)',
                           'UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class'
                           ], inplace=True)
subject_data.head(3)

,PATNO,Visit ID,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,Identify self as White,Education_Years,AGE_AT_VISIT,MDS-UPDRS Part I (Patient Questionnaire) Total Score,MDS-UPDRS Part II Total Score,MDS-UPDRS Part III Total Score,MDS-UPDRS Part IV Total Score,MDS-UPDRS Total Score,BMI,Ortostatic_Hypotension,UPDRS_III_ProgressionType
0,100006,V04_V06,0,0,0,0,0,1965,0,1,15.0,56.7,8,9.0,17,2.0,36.0,35.493827,False,Substantial improv.
1,100007,V04_V06,0,0,0,0,0,1953,1,1,19.0,68.4,2,7.0,23,0.0,32.0,22.985398,False,Substantial improv.
2,100012,V04_V06,0,0,0,0,0,1955,0,1,18.0,67.0,6,5.0,14,0.0,25.0,31.130098,False,No significant change.

In [44]:
dict_min_age = {}
for patno in subject_data['PATNO'].unique():
    selceted_data = subject_data.loc[subject_data['PATNO'] == patno,'AGE_AT_VISIT']
    min_age = selceted_data.min()
    if min_age<=60:
        type_age=1
    else:
        type_age=0
    dict_min_age[patno] = type_age

subject_data['Age_Type'] = subject_data['PATNO'].map(dict_min_age)
subject_data.head(3)

,PATNO,Visit ID,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,Identify self as White,...,AGE_AT_VISIT,MDS-UPDRS Part I (Patient Questionnaire) Total Score,MDS-UPDRS Part II Total Score,MDS-UPDRS Part III Total Score,MDS-UPDRS Part IV Total Score,MDS-UPDRS Total Score,BMI,Ortostatic_Hypotension,UPDRS_III_ProgressionType,Age_Type
0,100006,V04_V06,0,0,0,0,0,1965,0,1,...,56.7,8,9.0,17,2.0,36.0,35.493827,False,Substantial improv.,1
1,100007,V04_V06,0,0,0,0,0,1953,1,1,...,68.4,2,7.0,23,0.0,32.0,22.985398,False,Substantial improv.,0
2,100012,V04_V06,0,0,0,0,0,1955,0,1,...,67.0,6,5.0,14,0.0,25.0,31.130098,False,No significant change.,0

In [45]:
#'Ortostatic_Hypotension'
subject_data['Ortostatic_Hypotension'] = subject_data['Ortostatic_Hypotension'].map({True: 1, False: 0})
# 'UPDRS_III_ProgressionType'
subject_data['UPDRS_III_ProgressionType'] = subject_data['UPDRS_III_ProgressionType'].map({'Substantial improv.': -1, 'No significant change.': 0,'Substantial progress.': 1})

subject_data['subject_visit'] = subject_data['PATNO'].astype(str) + '_' + subject_data['Visit ID'].astype(str)
subject_data.drop(columns=['PATNO','Visit ID'], inplace=True)

subject_data.head(3)

,RBD at Enrollment,Parkin Mutation at Enrollment,LRRK2 Mutation at Enrollment,SNCA Mutation at Enrollment,GBA Mutation at Enrollment,Birth Date,Sex of participant at birth,Identify self as White,Education_Years,AGE_AT_VISIT,MDS-UPDRS Part I (Patient Questionnaire) Total Score,MDS-UPDRS Part II Total Score,MDS-UPDRS Part III Total Score,MDS-UPDRS Part IV Total Score,MDS-UPDRS Total Score,BMI,Ortostatic_Hypotension,UPDRS_III_ProgressionType,Age_Type,subject_visit
0,0,0,0,0,0,1965,0,1,15.0,56.7,8,9.0,17,2.0,36.0,35.493827,0,-1,1,100006_V04_V06
1,0,0,0,0,0,1953,1,1,19.0,68.4,2,7.0,23,0.0,32.0,22.985398,0,-1,0,100007_V04_V06
2,0,0,0,0,0,1955,0,1,18.0,67.0,6,5.0,14,0.0,25.0,31.130098,0,0,0,100012_V04_V06

## Data Download

In [46]:
subject_data.to_csv(ROOT / 'DATA_MODEL_Dev/Subject_data_models.csv', index=False)

# Motor Data

In [47]:
motor_data = pd.read_csv(ROOT / motor)
motor_data['subject_visit'] = motor_data['PATNO'].astype(str) + '_' + motor_data['Visit ID'].astype(str)
motor_data.drop(columns=['PATNO','Visit ID'], inplace=True)
motor_data.head(3)

,SCHWAB & ENGLAND ADL,MDS-UPDRS Part I (Patient Questionnaire) Total Score,MDS-UPDRS Part II Total Score,Does participant have DBS,MDS-UPDRS Part III Total Score,3.21 HOEHN AND YAHR STAGE,MDS-UPDRS Part IV Total Score,DBS_Transition_Visit,DBS_Post_Transition,MDS-UPDRS Total Score 1YearProg,...,Δ UPDRS_III_1Y,Δ UPDRS_IV_1Y,UPDRS_I_Class,UPDRS_II_Class,UPDRS_III_Class,UPDRS_IV_Class,UPDRS_I_ProgressionType,UPDRS_II_ProgressionType,UPDRS_III_ProgressionType,subject_visit
0,90,6,5.0,0,35,2,0.0,False,0.0,37.0,...,-9,0.0,Mild,Mild,Moderate,Mild,No significant change.,No significant change.,Substantial improv.,3001_V10_V12
1,85,9,10.0,0,53,3,0.0,False,0.0,59.0,...,-14,0.0,Mild,Mild,Moderate,Mild,No significant change.,No significant change.,Substantial improv.,3003_V10_V12
2,80,11,16.0,0,18,2,7.0,False,0.0,70.0,...,16,-2.0,Moderate,Moderate,Mild,Moderate,No significant change.,No significant change.,Substantial progress.,3010_V10_V12

## Data Selection

In [48]:
motor_data['UPDRS_I_Class'] = motor_data['UPDRS_I_Class'].map({'Mild': 0, 'Moderate': 1})
motor_data['UPDRS_II_Class'] = motor_data['UPDRS_II_Class'].map({'Mild': 0, 'Moderate': 1})
motor_data['UPDRS_III_Class'] = motor_data['UPDRS_III_Class'].map({'Mild': 0, 'Moderate': 1})
motor_data['UPDRS_IV_Class'] = motor_data['UPDRS_IV_Class'].map({'Mild': 0, 'Moderate': 1})
motor_data['Type_change_updrs3'] = motor_data['Δ UPDRS_III_1Y'].apply(lambda x: 'Positive' if x <= 0 else 'Negative')


motor_data['DBS_Transition_Visit']= motor_data['DBS_Transition_Visit'].map({True: 1, False: 0})

motor_data.drop(columns=['MDS-UPDRS Total Score 1YearProg','UPDRS_III_1YearProg',
                    'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 
                    'Δ UPDRS_IV_1Y', 'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType'], inplace=True)

numeric_cols = motor_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = motor_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['SCHWAB & ENGLAND ADL', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'Does participant have DBS', 'MDS-UPDRS Part III Total Score', '3.21 HOEHN AND YAHR STAGE', 'MDS-UPDRS Part IV Total Score', 'DBS_Transition_Visit', 'DBS_Post_Transition', 'MDS-UPDRS Total Score', 'Δ UPDRS_III_1Y', 'UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class']
Categorical Columns: ['UPDRS_III_ProgressionType', 'subject_visit', 'Type_change_updrs3']

## Data Download

In [49]:
motor_data.to_csv(ROOT / 'DATA_MODEL_Dev/Motor_data_models.csv', index=False)

# Cognitive Data

In [50]:
cognitive_data = pd.read_csv(ROOT / cognitive)
cognitive_data['subject_visit'] = cognitive_data['PATNO'].astype(str) + '_' + cognitive_data['Visit ID'].astype(str)
cognitive_data.drop(columns=['PATNO','Visit ID'], inplace=True)
cognitive_data.head(3)

,HVLT Total Recall Score,HVLT Delayed Recall Score,HVLT Retention Score,HVLT Recognition Discrimination Index Score,Motor Exam assessment,Coordination assessment,Sensory Exam assessment,Reflexes assessment,CN II-XII assessment,STAI PART I Score,...,Δ UPDRS_IV_1Y,UPDRS_I_Class,UPDRS_II_Class,UPDRS_III_Class,UPDRS_IV_Class,UPDRS_I_ProgressionType,UPDRS_II_ProgressionType,UPDRS_III_ProgressionType,Perfil_LPA,subject_visit
0,60.0,56.0,48.0,44.0,Normal,Normal,Abnormal,Abnormal,Normal,53.0,...,0.0,Mild,Mild,Moderate,Mild,No significant change.,No significant change.,Substantial improv.,Stability,3001_V10_V12
1,53.0,61.0,62.0,56.0,Normal,Normal,Abnormal,Abnormal,Normal,51.0,...,0.0,Mild,Mild,Moderate,Mild,No significant change.,No significant change.,Substantial improv.,Stability,3003_V10_V12
2,35.0,44.0,56.0,30.0,Normal,Normal,Normal,Abnormal,Normal,44.0,...,-2.0,Moderate,Moderate,Mild,Moderate,No significant change.,No significant change.,Substantial progress.,General Progress.,3010_V10_V12

## Data Selection

In [51]:
cognitive_data['UPDRS_III_ProgressionType'] = cognitive_data['UPDRS_III_ProgressionType'].map({'Substantial improv.': -1, 'No significant change.': 0,'Substantial progress.': 1})
cognitive_data['Has Depression']= cognitive_data['Has Depression'].map({True: 1, False: 0})
neuro_cols = ['Motor Exam assessment', 'Coordination assessment', 'Sensory Exam assessment', 'Reflexes assessment', 'CN II-XII assessment']
for col in neuro_cols:
    cognitive_data[col] = cognitive_data[col].map({'Normal': 1, 'Abnormal': 0})

cognitive_data.drop(columns=['UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class',
                             'UPDRS_IV_Class', 'UPDRS_I_ProgressionType', 
                             'UPDRS_II_ProgressionType', 'UPDRS_III_1YearProg','MDS-UPDRS Total Score 1YearProg',
                             'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score',
                             'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y'], inplace=True)

numeric_cols = cognitive_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = cognitive_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['HVLT Total Recall Score', 'HVLT Delayed Recall Score', 'HVLT Retention Score', 'HVLT Recognition Discrimination Index Score', 'Motor Exam assessment', 'Coordination assessment', 'Sensory Exam assessment', 'Reflexes assessment', 'CN II-XII assessment', 'STAI PART I Score', 'STAI PART II Score', 'STAI Total Score', 'GDS Short Score', 'Has Depression', 'Semantic Fluency Scaled Score', 'MoCA Total Score', 'VISUOSPATIAL_EXECUTIVE', 'NAMING', 'ATTENTION', 'LANGUAGE', 'ABSTRACTION', 'DELAYED_RECALL', 'ORIENTATION', 'Letter-Number Sequencing Scaled Score', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'Symbol Digit Modalities Test Total Correct', 'Benton Judgement of Line Orientation Scaled Score', 'MDS-UPDRS Total Score', 'UPDRS_III_ProgressionType']
Categorical Columns: ['Perfil_LPA', 'subject_visit']

## Data Download

In [52]:
cognitive_data.to_csv(ROOT / 'DATA_MODEL_Dev/Cognitive_data_models.csv', index=False)

# Sleep Data

In [53]:
sleep_data = pd.read_csv(ROOT / sleep)
sleep_data['subject_visit'] = sleep_data['PATNO'].astype(str) + '_' + sleep_data['Visit ID'].astype(str)
sleep_data.drop(columns=['PATNO','Visit ID'], inplace=True)
sleep_data.head(3)

,Sitting and reading,Watching TV,"Sitting, inactive in a public place",As a passenger in a car for an hour,Lying down to rest in the afternoon,Sitting and talking to someone,Sitting quietly after lunch,"In a car, while stopped in traffic",Epworth Sleepiness Scale Score,MDS-UPDRS Part I (Patient Questionnaire) Total Score,...,UPDRS_IV_Class,UPDRS_I_ProgressionType,UPDRS_II_ProgressionType,UPDRS_III_ProgressionType,rbd_status,dream_behavior_score,neuro_score,rbd_summary_score,eps_class,subject_visit
0,1,2,1.0,0,2,0.0,0,0,6.0,6,...,Mild,No significant change.,No significant change.,Substantial improv.,RBD Positive,6,1,7,Normal,3001_V10_V12
1,1,1,0.0,3,1,0.0,0,0,6.0,9,...,Mild,No significant change.,No significant change.,Substantial improv.,RBD Negative,1,1,2,Normal,3003_V10_V12
2,2,3,1.0,0,3,1.0,1,0,11.0,11,...,Moderate,No significant change.,No significant change.,Substantial progress.,RBD Positive,7,1,8,Normal,3010_V10_V12

## Data Selection

In [54]:
numeric_cols = sleep_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = sleep_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['Sitting and reading', 'Watching TV', 'Sitting, inactive in a public place', 'As a passenger in a car for an hour', 'Lying down to rest in the afternoon', 'Sitting and talking to someone', 'Sitting quietly after lunch', 'In a car, while stopped in traffic', 'Epworth Sleepiness Scale Score', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score', 'Vivid Dreams', 'Aggressive or Action-packed dreams', 'nocturnal behaviour', 'move arms/legs during sleep', 'hurt bed partner', 'speaking in sleep', 'sudden limb movements', 'complex movements', 'things fell down', 'my movements awake me', 'remember dreams', 'sleep is disturbed', 'Stroke', 'Head trauma', 'Parkinsonism', 'Restless Leg Syndrome (RLS)', 'Narcolepsy', 'Depression', 'Epilepsy', 'Inflammatory disease of the brain', 'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg', 'MDS-UPDRS Total Score', 'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y', 'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y', 'dream_behavior_score', 'neuro_score', 'rbd_summary_score']
Categorical Columns: ['UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class', 'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType', 'UPDRS_III_ProgressionType', 'rbd_status', 'eps_class', 'subject_visit']

## Data Selection

In [55]:
sleep_data['UPDRS_III_ProgressionType'] = sleep_data['UPDRS_III_ProgressionType'].map({'Substantial improv.': -1, 'No significant change.': 0,'Substantial progress.': 1})
sleep_data['rbd_status']=sleep_data['rbd_status'].map({'RBD Positive':1, 'RBD Negative':0})
sleep_data['eps_class']=sleep_data['eps_class'].map({'Normal':0,'Excessive Sleepiness':1})

sleep_data.drop(columns=['UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class', 
                          'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType',
                          'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg',
                          'MDS-UPDRS Total Score', 'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y',
                          'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y',], inplace=True)

numeric_cols = sleep_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = sleep_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['Sitting and reading', 'Watching TV', 'Sitting, inactive in a public place', 'As a passenger in a car for an hour', 'Lying down to rest in the afternoon', 'Sitting and talking to someone', 'Sitting quietly after lunch', 'In a car, while stopped in traffic', 'Epworth Sleepiness Scale Score', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score', 'Vivid Dreams', 'Aggressive or Action-packed dreams', 'nocturnal behaviour', 'move arms/legs during sleep', 'hurt bed partner', 'speaking in sleep', 'sudden limb movements', 'complex movements', 'things fell down', 'my movements awake me', 'remember dreams', 'sleep is disturbed', 'Stroke', 'Head trauma', 'Parkinsonism', 'Restless Leg Syndrome (RLS)', 'Narcolepsy', 'Depression', 'Epilepsy', 'Inflammatory disease of the brain', 'UPDRS_III_ProgressionType', 'rbd_status', 'dream_behavior_score', 'neuro_score', 'rbd_summary_score', 'eps_class']
Categorical Columns: ['subject_visit']

# DATA DOWNLOAD

In [56]:
sleep_data.to_csv(ROOT / 'DATA_MODEL_Dev/Sleep_data_models.csv', index=False)

# LEDD Medication Data

In [57]:
ledd_data = pd.read_csv(ROOT / ledd)
ledd_data['subject_visit'] = ledd_data['PATNO'].astype(str) + '_' + ledd_data['Visit ID'].astype(str)
ledd_data.drop(columns=['PATNO','Visit ID'], inplace=True)
ledd_data.head(3)

,NO PD Medication,amantadine_Dose_Strength_mean,amantadine_Total_mg_per_day_mean,apomorphine_Dose_Strength_mean,apomorphine_Total_mg_per_day_mean,benserazide_Dose_Strength_mean,benserazide_Total_mg_per_day_mean,carbidopa_Dose_Strength_mean,carbidopa_Total_mg_per_day_mean,entacapone_Dose_Strength_mean,...,Δ UPDRS_III_1Y,Δ UPDRS_IV_1Y,UPDRS_I_Class,UPDRS_II_Class,UPDRS_III_Class,UPDRS_IV_Class,UPDRS_I_ProgressionType,UPDRS_II_ProgressionType,UPDRS_III_ProgressionType,subject_visit
0,1,0.0,0.0,0.0,0.0,0.0,0.0,27.083333,106.250000,0.0,...,-9,0.0,Mild,Mild,Moderate,Mild,No significant change.,No significant change.,Substantial improv.,3001_V10_V12
1,1,105.0,210.0,0.0,0.0,0.0,0.0,27.083333,104.166667,0.0,...,-14,0.0,Mild,Mild,Moderate,Mild,No significant change.,No significant change.,Substantial improv.,3003_V10_V12
2,0,0.0,0.0,0.0,0.0,0.0,0.0,52.083333,200.000000,0.0,...,16,-2.0,Moderate,Moderate,Mild,Moderate,No significant change.,No significant change.,Substantial progress.,3010_V10_V12

## Data Selection

In [58]:
ledd_data['UPDRS_III_ProgressionType'] = ledd_data['UPDRS_III_ProgressionType'].map({'Substantial improv.': -1, 'No significant change.': 0,'Substantial progress.': 1})

ledd_data.drop(columns=['UPDRS_I_Class', 'UPDRS_II_Class', 'UPDRS_III_Class', 'UPDRS_IV_Class', 
                          'UPDRS_I_ProgressionType', 'UPDRS_II_ProgressionType',
                          'MDS-UPDRS Total Score 1YearProg', 'UPDRS_III_1YearProg',
                          'MDS-UPDRS Total Score', 'Δ TOTAL_UPDRS_1Y', 'Δ UPDRS_I_1Y',
                          'Δ UPDRS_II_1Y', 'Δ UPDRS_III_1Y', 'Δ UPDRS_IV_1Y','All_Medications'], inplace=True)

numeric_cols = ledd_data.select_dtypes(include=['int64', 'float64']).columns.tolist()
categorical_cols = ledd_data.select_dtypes(include=['object','bool']).columns.tolist()
print("Numeric Columns:", numeric_cols)
print("Categorical Columns:", categorical_cols)

Numeric Columns: ['NO PD Medication', 'amantadine_Dose_Strength_mean', 'amantadine_Total_mg_per_day_mean', 'apomorphine_Dose_Strength_mean', 'apomorphine_Total_mg_per_day_mean', 'benserazide_Dose_Strength_mean', 'benserazide_Total_mg_per_day_mean', 'carbidopa_Dose_Strength_mean', 'carbidopa_Total_mg_per_day_mean', 'entacapone_Dose_Strength_mean', 'entacapone_Total_mg_per_day_mean', 'levodopa_Dose_Strength_mean', 'levodopa_Total_mg_per_day_mean', 'piribedil_Dose_Strength_mean', 'piribedil_Total_mg_per_day_mean', 'pramipexole_Dose_Strength_mean', 'pramipexole_Total_mg_per_day_mean', 'rasagiline_Dose_Strength_mean', 'rasagiline_Total_mg_per_day_mean', 'ropinirole_Dose_Strength_mean', 'ropinirole_Total_mg_per_day_mean', 'rotigotine_Dose_Strength_mean', 'rotigotine_Total_mg_per_day_mean', 'safinamide_Dose_Strength_mean', 'safinamide_Total_mg_per_day_mean', 'selegiline_Dose_Strength_mean', 'selegiline_Total_mg_per_day_mean', 'trihexyphenidyl_Dose_Strength_mean', 'trihexyphenidyl_Total_mg_per_day_mean', 'zonisamide_Dose_Strength_mean', 'zonisamide_Total_mg_per_day_mean', 'amantadine_Dose_Strength_std', 'amantadine_Total_mg_per_day_std', 'apomorphine_Dose_Strength_std', 'apomorphine_Total_mg_per_day_std', 'benserazide_Dose_Strength_std', 'benserazide_Total_mg_per_day_std', 'carbidopa_Dose_Strength_std', 'carbidopa_Total_mg_per_day_std', 'entacapone_Dose_Strength_std', 'entacapone_Total_mg_per_day_std', 'levodopa_Dose_Strength_std', 'levodopa_Total_mg_per_day_std', 'piribedil_Dose_Strength_std', 'piribedil_Total_mg_per_day_std', 'pramipexole_Dose_Strength_std', 'pramipexole_Total_mg_per_day_std', 'rasagiline_Dose_Strength_std', 'rasagiline_Total_mg_per_day_std', 'ropinirole_Dose_Strength_std', 'ropinirole_Total_mg_per_day_std', 'rotigotine_Dose_Strength_std', 'rotigotine_Total_mg_per_day_std', 'safinamide_Dose_Strength_std', 'safinamide_Total_mg_per_day_std', 'selegiline_Dose_Strength_std', 'selegiline_Total_mg_per_day_std', 'trihexyphenidyl_Dose_Strength_std', 'trihexyphenidyl_Total_mg_per_day_std', 'zonisamide_Dose_Strength_std', 'zonisamide_Total_mg_per_day_std', 'MDS-UPDRS Part I (Patient Questionnaire) Total Score', 'MDS-UPDRS Part II Total Score', 'MDS-UPDRS Part III Total Score', 'MDS-UPDRS Part IV Total Score', 'UPDRS_III_ProgressionType']
Categorical Columns: ['subject_visit']