In [1]:
import sys, os
ROOT = "/Users/fserracrespi/Desktop/PD_PROJECT_UOFL" 
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)
from utils.Decode import decoder_DF
from utils.dataframe_cols import cols_asignacion2
from utils.Prog_df import check_progression
from utils.Prog_df import progression_csv_upgrade
from utils.Prog_df import check_progression_multi
from utils.Prog_df import progression_multi_csv_upgrade
from utils.Prog_df import visit_csv_upgrade
from utils.Prog_df import check_visits
import json
from collections import defaultdict
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from scipy.stats import kurtosis, skew
import re
import math

In [2]:
path2='/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Study_Docs/Data___Databases/DATA/Data_Dictionary_-_Harmonized_12Sep2025.csv'
path3='/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Study_Docs/Data___Databases/DATA/Code_List_-_Harmonized_12Sep2025.csv'
orden_visitas = ["BL", "V04", "V06", "V08", "V10", "V12"]
code_cols=pd.read_csv(path2, dtype=str)
code_rows=pd.read_csv(path3, dtype=str)
PATNOs = pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/PD_CSV_CLEAN/Relevant_presnece_PATNO', dtype=str)['PATNO'].tolist()
print(f'Total PATNOs to process: {len(PATNOs)}')

Total PATNOs to process: 1056

# MDS_UPDRS

## UPDRS 1

In [3]:
updrs1Q_data=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Motor Assesments/Motor___MDS-UPDRS/DATA/MDS-UPDRS_Part_I_Patient_Questionnaire_12Sep2025.csv', dtype=str)
updrs1Q_data=updrs1Q_data[updrs1Q_data['PATNO'].isin(PATNOs)]
updrs1Q_data=decoder_DF(updrs1Q_data, code_rows, code_cols, module='NUPDRS1P')
updrs1Q_data=updrs1Q_data.loc[updrs1Q_data['Visit ID'].isin(["BL", "V04", "V06", "V08", "V10", "V12"]),:]
updrs1Q_data['Visit ID'] = pd.Categorical(updrs1Q_data['Visit ID'], categories=orden_visitas, ordered=True)
updrs1Q_data=updrs1Q_data.sort_values(by=['PATNO', 'Visit ID']).reset_index(drop=True)     
updrs1Q_data=updrs1Q_data.loc[updrs1Q_data['Primary Source of Information']=='Patient',:]
updrs1Q_data=updrs1Q_data[['PATNO', 'Visit ID','MDS-UPDRS Part I (Patient Questionnaire) Total Score']]
print(f"UPDRS1Q data shape after filtering by PATNOs: {updrs1Q_data['PATNO'].nunique()} unique PATNOs, {updrs1Q_data.shape[0]} total records")
updrs1Q_data.head()

UPDRS1Q data shape after filtering by PATNOs: 1038 unique PATNOs, 3692 total records

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Decode.py:81: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace('NaN', np.nan, inplace=True)

    PATNO Visit ID MDS-UPDRS Part I (Patient Questionnaire) Total Score
0  100001       BL                                                  6
1  100001      V04                                                  4
2  100001      V06                                                  4
3  100001      V08                                                  3
4  100001      V10                                                  5

In [4]:
updrs1Q_data.isna().sum()

PATNO                                                   0
Visit ID                                                0
MDS-UPDRS Part I (Patient Questionnaire) Total Score    0
dtype: int64

## UPDRS 2

In [5]:
updrs2_data=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Motor Assesments/Motor___MDS-UPDRS/DATA/MDS_UPDRS_Part_II__Patient_Questionnaire_12Sep2025.csv', dtype=str)
updrs2_data=updrs2_data[updrs2_data['PATNO'].isin(PATNOs)]
updrs2_data=decoder_DF(updrs2_data, code_rows, code_cols, module='NUPDRS1P2P')
updrs2_data=updrs2_data.loc[updrs2_data['Primary Source of Information']=='1', :]
updrs2_data=updrs2_data.loc[updrs2_data['Visit ID'].isin(["BL", "V04", "V06", "V08", "V10", "V12"]),:]
updrs2_data['Visit ID'] = pd.Categorical(updrs2_data['Visit ID'], categories=orden_visitas, ordered=True)
updrs2_data=updrs2_data.sort_values(by=['PATNO', 'Visit ID']).reset_index(drop=True)     
updrs2_data=updrs2_data[['PATNO', 'Visit ID','MDS-UPDRS Part II Total Score']]
print(f"UPDRS1Q data shape after filtering by PATNOs: {updrs2_data['PATNO'].nunique()} unique PATNOs, {updrs2_data.shape[0]} total records")
updrs2_data.head()

UPDRS1Q data shape after filtering by PATNOs: 1038 unique PATNOs, 3695 total records

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Decode.py:81: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace('NaN', np.nan, inplace=True)

    PATNO Visit ID MDS-UPDRS Part II Total Score
0  100001       BL                            10
1  100001      V04                             8
2  100001      V06                            10
3  100001      V08                            11
4  100001      V10                            13

In [6]:
updrs2_data.isna().sum()

PATNO                            0
Visit ID                         0
MDS-UPDRS Part II Total Score    6
dtype: int64

In [7]:
problematic_patnos=updrs2_data.loc[updrs2_data['MDS-UPDRS Part II Total Score'].isna(),'PATNO'].to_list()

# --- Función para rellenar valores faltantes ---
def fill_missing_values(lista_val):
    lista_val = lista_val.copy()
    for i in range(1, len(lista_val)):
        if np.isnan(lista_val[i]):
            lista_val[i] = lista_val[i-1]
    for i in range(len(lista_val)-2, -1, -1):
        if np.isnan(lista_val[i]):
            lista_val[i] = lista_val[i+1]
    return lista_val


# --- Aplicar la función a cada PATNO ---

for patno in problematic_patnos:
    mask = updrs2_data['PATNO'] == patno
    valores_originales = updrs2_data.loc[mask, 'MDS-UPDRS Part II Total Score'].tolist()
    valores_rellenos = fill_missing_values([float(v) if pd.notna(v) else np.nan for v in valores_originales])
    updrs2_data.loc[mask, 'MDS-UPDRS Part II Total Score'] = valores_rellenos

updrs2_data.isna().sum()

PATNO                            0
Visit ID                         0
MDS-UPDRS Part II Total Score    0
dtype: int64

## UPRDS 3

In [8]:
updrs3_data=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Motor Assesments/Motor___MDS-UPDRS/DATA/MDS-UPDRS_Part_III_12Sep2025.csv', dtype=str)
print(updrs3_data.shape)
print(updrs3_data["PATNO"].nunique())
updrs3_data=decoder_DF(updrs3_data, code_rows, code_cols, module='NUPDRDOSE3')
updrs3_data=updrs3_data[updrs3_data['PATNO'].isin(PATNOs)]
updrs3_data=updrs3_data.loc[updrs3_data['Visit ID'].isin(["BL", "V04", "V06", "V08", "V10", "V12"]),:]
updrs3_data['Visit ID'] = pd.Categorical(updrs3_data['Visit ID'], categories=orden_visitas, ordered=True)
updrs3_data=updrs3_data.sort_values(by=['PATNO', 'Visit ID']).reset_index(drop=True)     
print(f"UPDRS1Q data shape after filtering by PATNOs: {updrs3_data['PATNO'].nunique()} unique PATNOs, {updrs3_data.shape[0]} total records")

rel_col=['PATNO', 'Visit ID','Is the participant on medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?',
       'Which functional state is the participant currently in?',
       'Hours between last dose of PD medication and NUPDRS3 exam',
       'Hours between DBS device turned on and NUPDRS3 exam',
       'Hours between DBS device turned off and NUPDRS3 exam',
       'Is subject on medication for PD', 'Does participant have DBS',
       'First Part III exam OFF or ON', 'OFF exam performed',
       'Reason OFF exam not performed',
       'Was DBS turned off at the appropriate time?',
       'Time DBS turned off before OFF exam', 'ON exam performed',
       'Reason ON exam not performed',
       'Has the participant had high-intensity focused ultrasound?',
       'Was DBS turned on at the appropriate time?',
       'Time DBS turned on before ON exam', 'Date of most recent PD med dose',
       'Time of most recent PD med dose', 'Date exam was administered',
       'Time exam was administered','MDS-UPDRS Part III Total Score','3.19 Were dyskinesias present',
       '3.20 Did movements interfere with rating','3.21 HOEHN AND YAHR STAGE']
       
updrs3_data=updrs3_data[rel_col]

updrs3_data.head()

(34531, 65)
4544
UPDRS1Q data shape after filtering by PATNOs: 1056 unique PATNOs, 5835 total records

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Decode.py:81: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace('NaN', np.nan, inplace=True)

,PATNO,Visit ID,Is the participant on medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?,Which functional state is the participant currently in?,Hours between last dose of PD medication and NUPDRS3 exam,Hours between DBS device turned on and NUPDRS3 exam,Hours between DBS device turned off and NUPDRS3 exam,Is subject on medication for PD,Does participant have DBS,First Part III exam OFF or ON,...,Was DBS turned on at the appropriate time?,Time DBS turned on before ON exam,Date of most recent PD med dose,Time of most recent PD med dose,Date exam was administered,Time exam was administered,MDS-UPDRS Part III Total Score,3.19 Were dyskinesias present,3.20 Did movements interfere with rating,3.21 HOEHN AND YAHR STAGE
0,100001,BL,0,NaN,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,10/2020,NaN,24,0,NaN,2
1,100001,V04,0,NaN,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,11/2021,NaN,33,0,0,2
2,100001,V06,0,NaN,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,11/2022,10:03:00,37,0,NaN,2
3,100001,V08,0,NaN,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,11/2023,10:11:00,43,0,NaN,2
4,100001,V10,0,NaN,NaN,NaN,NaN,0,0,NaN,...,NaN,NaN,NaN,NaN,09/2024,09:59:00,43,0,NaN,2

In [9]:
updrs3_data.shape

(5835, 27)

In [10]:
cols_study=['PATNO','Visit ID','Is the participant on medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?','Which functional state is the participant currently in?',
            'Is subject on medication for PD','Does participant have DBS','MDS-UPDRS Part III Total Score','3.21 HOEHN AND YAHR STAGE']

df=updrs3_data[cols_study].copy()

In [11]:

cond = df['Is the participant on medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?'] == '0'

df.loc[cond, 'Which functional state is the participant currently in?'] = 'Not Med-Surg'

cols = [
    'Is subject on medication for PD',
    'Does participant have DBS',
]

df.loc[cond, cols] = '0'
df['Does participant have DBS']=df['Does participant have DBS'].fillna('0')
df.isna().sum()

df.loc[df.duplicated(subset=['PATNO', 'Visit ID']),:]

df['Which functional state is the participant currently in?'].value_counts()
mask_med_on = df['Which functional state is the participant currently in?']=='ON'
mask_DBS_on = df['Does participant have DBS']=='1'
df_severity=df.loc[mask_med_on | mask_DBS_on, :].copy()
df_severity.isna().sum()
print(df_severity.shape)
df_severity.dropna(how='any', inplace=True)
print(df_severity.shape)

df_severity = (
    df_severity.sort_values('Which functional state is the participant currently in?', ascending=False)
      .drop_duplicates(subset=['PATNO', 'Visit ID'], keep='first')
)

updrs3_data=df_severity.copy()
updrs3_data.drop(columns=['Which functional state is the participant currently in?'], inplace=True)

(2390, 8)
(2255, 8)

In [12]:
updrs3_data

,PATNO,Visit ID,Is the participant on medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?,Is subject on medication for PD,Does participant have DBS,MDS-UPDRS Part III Total Score,3.21 HOEHN AND YAHR STAGE
8,100002,V06,1,1,0,21,2
4303,40586,V10,1,1,0,14,2
4291,40585,V10,1,1,0,17,2
4294,40585,V12,1,1,0,8,2
4295,40586,BL,1,1,0,12,2
...,...,...,...,...,...,...,...
2234,218338,V06,1,1,0,9,2
2237,218340,V04,1,1,0,6,1
2239,218340,V06,1,1,0,10,1
5210,50746,BL,1,1,1,11,2
5547,58141,V08,1,1,1,55,2

## UPDRS 4

In [13]:
updrs4_data=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Motor Assesments/Motor___MDS-UPDRS/DATA/MDS-UPDRS_Part_IV__Motor_Complications_12Sep2025.csv', dtype=str)
updrs4_data=updrs4_data[updrs4_data['PATNO'].isin(PATNOs)]
updrs4_data=decoder_DF(updrs4_data, code_rows, code_cols, module='NUPDRS4')

updrs4_data=updrs4_data.loc[updrs4_data['Visit ID'].isin(["BL", "V04", "V06", "V08", "V10", "V12"]),:]
rel_col=['PATNO', 'Visit ID','MDS-UPDRS Part IV Total Score']
updrs4_data['Visit ID'] = pd.Categorical(updrs4_data['Visit ID'], categories=orden_visitas, ordered=True)
updrs4_data=updrs4_data.sort_values(by=['PATNO', 'Visit ID']).reset_index(drop=True)     

print(f"UPDRS4 data shape after filtering by PATNOs: {updrs4_data['PATNO'].nunique()} unique PATNOs, {updrs4_data.shape[0]} total records")
updrs4_data=updrs4_data[rel_col]

updrs4_data.isna().sum()

UPDRS4 data shape after filtering by PATNOs: 838 unique PATNOs, 2480 total records

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Decode.py:81: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace('NaN', np.nan, inplace=True)

PATNO                             0
Visit ID                          0
MDS-UPDRS Part IV Total Score    10
dtype: int64

In [14]:
problematic_patnos=updrs4_data.loc[updrs4_data['MDS-UPDRS Part IV Total Score'].isna(),'PATNO'].to_list()

for patno in problematic_patnos:
    mask = updrs4_data['PATNO'] == patno
    valores_originales = updrs4_data.loc[mask, 'MDS-UPDRS Part IV Total Score'].tolist()
    valores_rellenos = fill_missing_values([float(v) if pd.notna(v) else np.nan for v in valores_originales])
    updrs4_data.loc[mask, 'MDS-UPDRS Part IV Total Score'] = valores_rellenos

updrs4_data.dropna(how='any',inplace=True)
updrs4_data.isna().sum()

PATNO                            0
Visit ID                         0
MDS-UPDRS Part IV Total Score    0
dtype: int64

# FINAL UPDRS

In [15]:
UPDRS=updrs1Q_data.merge(updrs2_data, on=['PATNO', 'Visit ID'], how='inner')
UPDRS=UPDRS.merge(updrs3_data, on=['PATNO', 'Visit ID'], how='inner')
print(UPDRS.shape)
UPDRS=UPDRS.merge(updrs4_data, on=['PATNO', 'Visit ID'], how='left')
print(UPDRS.shape)
UPDRS.isna().sum()
UPDRS.dropna(how='any', inplace=True)
UPDRS.isna().sum()

(2058, 9)
(2058, 10)

PATNO                                                                                                                    0
Visit ID                                                                                                                 0
MDS-UPDRS Part I (Patient Questionnaire) Total Score                                                                     0
MDS-UPDRS Part II Total Score                                                                                            0
Is the participant on medication or receiving deep brain stimulation for treating the symptoms of Parkinsons disease?    0
Is subject on medication for PD                                                                                          0
Does participant have DBS                                                                                                0
MDS-UPDRS Part III Total Score                                                                                           0
3.21 HOEHN AND YAHR STAGE                                                                                                0
MDS-UPDRS Part IV Total Score                                                                                            0
dtype: int64

In [16]:
UPDRS['DBS_Transition_Visit'] = False

for id in UPDRS['PATNO'].unique():
    data_patient = UPDRS.loc[UPDRS['PATNO'] == id].sort_values('Visit ID')
    vals = set(data_patient['Does participant have DBS'].astype(str))
    visits = data_patient['Visit ID'].values
    dbs_vals = data_patient['Does participant have DBS'].astype(int).values

    # Caso 1: todos 0 → nunca tuvo DBS
    if all(x == '0' for x in data_patient['Does participant have DBS'].tolist()):
        UPDRS.loc[UPDRS['PATNO'] == id, 'DBS_Transition_Visit'] = False

    # Caso 2: todos 1 → siempre tuvo DBS
    if all(x == '1' for x in data_patient['Does participant have DBS'].tolist()):
        # Marcar la primera visita como transición
        first_visit = visits[0]
        UPDRS.loc[(UPDRS['PATNO'] == id) & (UPDRS['Visit ID'] == first_visit), 'DBS_Transition_Visit'] = True
        print(f'Patient {id} has always had DBS, transition at visit {first_visit}, length {len(dbs_vals)}.')

    # Caso 3: tiene transición 0 → 1
    if {'0', '1'}.issubset(vals):
        trans_idx = next((i for i in range(1, len(dbs_vals)) if dbs_vals[i-1] == 0 and dbs_vals[i] == 1), None)
        if trans_idx is not None:
            transition_visit = visits[trans_idx]
            UPDRS.loc[(UPDRS['PATNO'] == id) & (UPDRS['Visit ID'] == transition_visit), 'DBS_Transition_Visit'] = True

        print(f'Patient {id} has mixed DBS status (transition at visit {transition_visit}), length {len(dbs_vals)}.')

Patient 100002 has mixed DBS status (transition at visit V10), length 3.
Patient 100268 has always had DBS, transition at visit V10, length 1.
Patient 100972 has always had DBS, transition at visit V04, length 3.
Patient 101038 has mixed DBS status (transition at visit V10), length 4.
Patient 146875 has mixed DBS status (transition at visit V06), length 2.
Patient 150110 has always had DBS, transition at visit V06, length 2.
Patient 211045 has mixed DBS status (transition at visit V06), length 2.
Patient 3010 has mixed DBS status (transition at visit V12), length 2.
Patient 3207 has always had DBS, transition at visit V08, length 2.
Patient 3229 has mixed DBS status (transition at visit V08), length 3.
Patient 3400 has mixed DBS status (transition at visit V12), length 4.
Patient 3964 has mixed DBS status (transition at visit V12), length 2.
Patient 40534 has mixed DBS status (transition at visit V12), length 3.
Patient 40538 has mixed DBS status (transition at visit V12), length 5.
Patient 40540 has mixed DBS status (transition at visit V10), length 4.
Patient 40713 has always had DBS, transition at visit BL, length 6.
Patient 41282 has mixed DBS status (transition at visit V04), length 5.
Patient 41829 has mixed DBS status (transition at visit V12), length 6.
Patient 42379 has mixed DBS status (transition at visit V12), length 5.
Patient 42448 has always had DBS, transition at visit BL, length 6.
Patient 42455 has mixed DBS status (transition at visit V10), length 5.
Patient 50028 has mixed DBS status (transition at visit V12), length 5.
Patient 50192 has mixed DBS status (transition at visit V06), length 5.
Patient 50746 has always had DBS, transition at visit BL, length 5.
Patient 51551 has always had DBS, transition at visit BL, length 6.
Patient 52062 has mixed DBS status (transition at visit V08), length 6.
Patient 53600 has mixed DBS status (transition at visit V04), length 5.
Patient 54161 has mixed DBS status (transition at visit V10), length 6.
Patient 55468 has mixed DBS status (transition at visit V08), length 3.
Patient 56558 has mixed DBS status (transition at visit V08), length 4.
Patient 57813 has mixed DBS status (transition at visit V06), length 4.
Patient 58141 has mixed DBS status (transition at visit V08), length 5.
Patient 70463 has mixed DBS status (transition at visit V04), length 4.
Patient 70818 has mixed DBS status (transition at visit V12), length 5.
Patient 71809 has mixed DBS status (transition at visit V08), length 6.
Patient 73935 has mixed DBS status (transition at visit V06), length 5.
Patient 74199 has mixed DBS status (transition at visit V12), length 2.
Patient 75505 has mixed DBS status (transition at visit V10), length 6.

In [17]:
for id in UPDRS['PATNO'].unique():
    data_patient = UPDRS.loc[UPDRS['PATNO'] == id].sort_values('Visit ID').copy()
    trans_flags = data_patient['DBS_Transition_Visit'].values
    visits = data_patient['Visit ID'].values

    # Si no hay transición, todo 0
    if not any(trans_flags):
        UPDRS.loc[UPDRS['PATNO'] == id, 'DBS_Post_Transition'] = 0
        continue

    # Si hay transición → buscar índice
    trans_idx = np.where(trans_flags)[0][0]

    # Asignar número de visitas después (entero)
    for j in range(len(visits)):
        post_val = max(0, j - trans_idx)
        UPDRS.loc[
            (UPDRS['PATNO'] == id) & (UPDRS['Visit ID'] == visits[j]),
            'DBS_Post_Transition'
        ] = int(post_val)

# Modified Schwab

In [18]:
schwab_data=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Motor Assesments/Motor___MDS-UPDRS/DATA/Modified_Schwab___England_Activities_of_Daily_Living_12Sep2025.csv', dtype=str)
schwab_data=schwab_data[schwab_data['PATNO'].isin(PATNOs)]

schwab_data.rename(columns={'EVENT_ID':'Visit ID'}, inplace=True)
schwab_data=schwab_data.loc[schwab_data['Visit ID'].isin(["BL", "V04", "V06", "V08", "V10", "V12"]),:]

schwab_data=schwab_data[['PATNO', 'Visit ID', 'MSEADLG']]
schwab_data.rename(columns={'MSEADLG':'SCHWAB & ENGLAND ADL'}, inplace=True)
print(f"SCHWAB data shape after filtering by PATNOs: {schwab_data['PATNO'].nunique()} unique PATNOs, {schwab_data.shape[0]} total records")
schwab_data

SCHWAB data shape after filtering by PATNOs: 1056 unique PATNOs, 3890 total records

        PATNO Visit ID SCHWAB & ENGLAND ADL
1        3001       BL                   95
9        3001      V04                   95
11       3001      V06                   95
13       3001      V08                   95
15       3001      V10                   90
...       ...      ...                  ...
28189  446733       BL                   95
28194  452611       BL                   80
28198  466157       BL                   80
28199  476236       BL                   90
28201  492876       BL                  100

[3890 rows x 3 columns]

# Features of PD

In [19]:
features_df=pd.read_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/DATA_COLLECTION/12_09_2025/Medical History/Medical/DATA/Features_of_Parkinsonism_12Sep2025.csv', dtype=str)
features_df=features_df[features_df['PATNO'].isin(PATNOs)]
features_df=decoder_DF(features_df, code_rows, code_cols, module='FEATPD')
features_df=features_df.loc[features_df['Visit ID'].isin(["BL", "V04", "V06", "V08", "V10", "V12"]),:]
relevant_cols=['PATNO', 'Visit ID','Bradykinesia is present and typical for parkinsonism','Postural disturbance is present and typical for parkinsonism'
                ,'Rigidity is present and typical for parkinsonism','Rest tremor is present and typical for parkinsonism']   
features_df=features_df[relevant_cols]
features_df.fillna('Yes', inplace=True)
features_df

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Decode.py:81: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df[col].replace('NaN', np.nan, inplace=True)

,PATNO,Visit ID,Bradykinesia is present and typical for parkinsonism,Postural disturbance is present and typical for parkinsonism,Rigidity is present and typical for parkinsonism,Rest tremor is present and typical for parkinsonism
6,3001,V06,Yes,No,Yes,Yes
7,3001,V08,Yes,Yes,Yes,Yes
8,3001,V10,Yes,No,Yes,Yes
9,3001,V12,Yes,Yes,Yes,Yes
24,3003,V06,Yes,No,Yes,No
...,...,...,...,...,...,...
23434,446733,BL,Yes,No,Yes,Yes
23439,452611,BL,Yes,Yes,No,No
23443,466157,BL,Yes,Yes,Yes,Yes
23444,476236,BL,Yes,No,Yes,Yes
23446,492876,BL,Yes,No,Yes,No

# ANALYSIS OF PROGRESSION

In [20]:
progression_csv_upgrade(UPDRS,prefix="UPDRS")
UPDRS.to_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/PD_CSV_CLEAN/FINAL DATA TEST CLEAN/FINAL_UPDRS_12SEP2025.csv', index=False)
cols_asignacion2(UPDRS,df_secundario='UPDRS',df_main='MOTOR')


progression_csv_upgrade(features_df,prefix="FeaturesPD")
features_df.to_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/PD_CSV_CLEAN/FINAL DATA TEST CLEAN/FINAL_FeaturesPD_12SEP2025.csv', index=False)
cols_asignacion2(features_df,df_secundario='FeaturesPD',df_main='MOTOR')

progression_csv_upgrade(schwab_data,prefix="SchwabADL")
schwab_data.to_csv('/Users/fserracrespi/Desktop/PD_Project_UofL/PD_DATA/PD_CSV_CLEAN/FINAL DATA TEST CLEAN/FINAL_SchwabADL_12SEP2025.csv', index=False)
cols_asignacion2(schwab_data,df_secundario='SchwabADL',df_main='MOTOR')

progression_multi_csv_upgrade(UPDRS,prefix="UPDRS")
progression_multi_csv_upgrade(features_df,prefix="FeaturesPD")
progression_multi_csv_upgrade(schwab_data,prefix="SchwabADL")

visit_csv_upgrade(UPDRS, prefix="UPDRS")
visit_csv_upgrade(features_df, prefix="FeaturesPD")
visit_csv_upgrade(schwab_data, prefix="SchwabADL")

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:59: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p1.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:65: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p2.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:71: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p3.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:77: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p4.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:83: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p5.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:88: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p6.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:94: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p7.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:100: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p8.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:105: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p9.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:111: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p10.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:117: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p11.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:123: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p12.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:129: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p13.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:135: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p14.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:140: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p15.fillna(False, inplace=True)

Progression CSV files updated successfully.
Progression CSV files updated successfully.
Progression CSV files updated successfully.
MULTI Progression CSV files updated successfully.
MULTI Progression CSV files updated successfully.
MULTI Progression CSV files updated successfully.

/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:193: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p1.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:199: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p2.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:205: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p3.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:211: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p4.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:217: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  p5.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:254: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pBL.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:260: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pV04.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:265: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pV06.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:271: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pV08.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:277: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pV10.fillna(False, inplace=True)
/Users/fserracrespi/Desktop/PD_PROJECT_UOFL/utils/Prog_df.py:283: FutureWarning: Downcasting object dtype arrays on .fillna, .ffill, .bfill is deprecated and will change in a future version. Call result.infer_objects(copy=False) instead. To opt-in to the future behavior, set `pd.set_option('future.no_silent_downcasting', True)`
  pV12.fillna(False, inplace=True)

Visits CSV files updated successfully.
Visits CSV files updated successfully.
Visits CSV files updated successfully.